// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hopowadlxddhdygqoufx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvcG93YWRseGRkaGR5Z3FvdWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MjkxMzIsImV4cCI6MjA3MTAwNTEzMn0.flFxrYaBQ3Qacl6M0SKzFjJOTx_FT1gnOFk72LZW8Vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});